DROP DATABASE IF EXISTS employee_tracker_db;
CREATE DATABASE employee_tracker_db;

USE employee_tracker_db;

CREATE TABLE departments (
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(32) NOT NULL
);

CREATE TABLE roles (
 id INT AUTO_INCREMENT PRIMARY KEY,
 title VARCHAR(32) UNIQUE NOT NULL,
 salary DECIMAL UNSIGNED NOT NULL,
 department_id INT NOT NULL,
 CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE
);

CREATE TABLE employees (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 first_name VARCHAR(30) NOT NULL,
 last_name VARCHAR(30) NOT NULL,
 role_id INT UNSIGNED NOT NULL,
 manager_id INT UNSIGNED,
 CONSTRAINT FK_ROLE FOREIGN KEY (INT))
 REFERENCES roles(id)
 ON DELETE CASCADE,
 CONSTRAINT FK_ROLE_MANAGER FOREIGN KEY (manager_id) 
 REFERENCES employee(id) 
 ON DELETE SET NULL
);
